### ISSUE TITLE
what is cripto

### ISSUE THREAD

**Issue by ryanrhee** [william-fields/witless#2]
i dont understand this
plis help

**Comment by william-fields** [comment]
https://www.wattpad.com/story/278853444-cripto-stories-unlimited

**Comment by ryanrhee** [comment]
im 12 what is this

**Comment by gcampos1712** [comment]
Hi 12, I’m dad

**Comment by william-fields** [comment]
Hi 12, I’m dad

**Comment by ryanrhee** [comment]
cripto crashed
